module:
  name: scopes-service 
  component: oauth2 
  repo: karmaksana-io/scopes-service

service:
  ports:
  - port: 80 
    targetPort: 80 
    protocol: TCP

configmap:
  envConfig: true 

liveness:
  httpGet:
    path: /
    port: 80

readiness:
  httpGet:
    path: /
    port: 80
