version: '3.7'

networks:
  intranet:

volumes:
  dev_mysql_db:
    external: true

services:
  scopes-backend:
    build: 
      context: .
      dockerfile: ./dev.Dockerfile
    container_name: scopes-backend
    ports:
      - "9526:9526"
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - dev-mysql-db
      # - redis
    networks:
      - intranet

  dev-mysql-db:
    container_name: dev-scopes-mysql
    image: mysql:8.0.25
    ports:
     - "3406:3406"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER:          admin
      MYSQL_PASSWORD:      12345678
      MYSQL_TCP_PORT: 3406
    volumes:
      - "dev_mysql_db:/var/lib/mysql"
    networks:
      - intranet
    platform: linux/x86_64

  phpmyadmin:
    container_name: dev-shared-pma
    image: phpmyadmin/phpmyadmin
    ports:
     - "8008:80"
    environment:
      PMA_HOST: dev-mysql-db
      PMA_PORT: 3406
    networks:
      - intranet
    depends_on:
      - dev-mysql-db
